// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnjbxDvXLFm0TF2nwu3SG0Y-YArmO3aBQ',
    appId: '1:809575672663:web:fa22aa7d50056c88a06c12',
    messagingSenderId: '809575672663',
    projectId: 'aisproject-80b23',
    authDomain: 'aisproject-80b23.firebaseapp.com',
    storageBucket: 'aisproject-80b23.firebasestorage.app',
    measurementId: 'G-FD07WZYXKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWhvUjqPsjHXpuJaFMtV3g3DDmdegq298',
    appId: '1:809575672663:android:56aceb2667d38830a06c12',
    messagingSenderId: '809575672663',
    projectId: 'aisproject-80b23',
    storageBucket: 'aisproject-80b23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-gcd6XliQKnKh_UASTqxn4pKtJqvJvXM',
    appId: '1:809575672663:ios:ad08676db603553ea06c12',
    messagingSenderId: '809575672663',
    projectId: 'aisproject-80b23',
    storageBucket: 'aisproject-80b23.firebasestorage.app',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-gcd6XliQKnKh_UASTqxn4pKtJqvJvXM',
    appId: '1:809575672663:ios:ad08676db603553ea06c12',
    messagingSenderId: '809575672663',
    projectId: 'aisproject-80b23',
    storageBucket: 'aisproject-80b23.firebasestorage.app',
    iosBundleId: 'com.example.practice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnjbxDvXLFm0TF2nwu3SG0Y-YArmO3aBQ',
    appId: '1:809575672663:web:caa03b537f68b8e5a06c12',
    messagingSenderId: '809575672663',
    projectId: 'aisproject-80b23',
    authDomain: 'aisproject-80b23.firebaseapp.com',
    storageBucket: 'aisproject-80b23.firebasestorage.app',
    measurementId: 'G-T0J46VSKLY',
  );
}
